### ISSUE TITLE
Specified value has invalid CRLF characters.

### ISSUE THREAD

**Issue by luuksommers** [mquekel/vsts-unicorn-sync#1]
We sometimes get invalid CRLF characters, I'm wondering if this is could be caused by the generated headers (mac/nonce), or is it something Azure DevOps related?

```
2019-01-30T12:21:43.8516173Z ##[section]Starting: Unicorn Sync
2019-01-30T12:21:43.8519406Z ==============================================================================
2019-01-30T12:21:43.8519569Z Task         : Unicorn Sync for Sitecore
2019-01-30T12:21:43.8519704Z Description  : Sync Unicorn configurations with the remote Powershell script.
2019-01-30T12:21:43.8519846Z Version      : 0.7.0
2019-01-30T12:21:43.8519940Z Author       : Martijn Quekel
2019-01-30T12:21:43.8520041Z Help         : 
2019-01-30T12:21:43.8520166Z ==============================================================================
2019-01-30T12:21:43.8548158Z Preparing task execution handler.
2019-01-30T12:21:44.5904341Z Executing the powershell script: D:\a\_tasks\UnicornSync_475ad458-6778-4e40-a8b5-5f983bea595d\0.7.0\start-sync.ps1
2019-01-30T12:21:44.5918951Z Starting Unicorn Sync.
2019-01-30T12:21:44.5919063Z 
2019-01-30T12:21:44.5919140Z 
2019-01-30T12:21:44.5919349Z This script is using Unicorn.psm1 from https://github.com/kamsar/Unicorn Copyright (c) 2018 Kam Figy
2019-01-30T12:21:44.5919559Z 
2019-01-30T12:21:44.5919651Z 
2019-01-30T12:24:44.5258406Z Sync-Unicorn: Executing Sync...
2019-01-30T12:24:44.5258981Z 
2019-01-30T12:24:44.5259199Z 
2019-01-30T12:24:44.6669776Z ##[error]System.Management.Automation.CmdletInvocationException: Specified value has invalid CRLF characters.
2019-01-30T12:24:44.6670526Z Parameter name: value ---> System.Management.Automation.RuntimeException: Specified value has invalid CRLF characters.
2019-01-30T12:24:44.6670768Z Parameter name: value ---> System.ArgumentException: Specified value has invalid CRLF characters.
2019-01-30T12:24:44.6670925Z Parameter name: value
2019-01-30T12:24:44.6671081Z    at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
2019-01-30T12:24:44.6671257Z    at System.Net.WebHeaderCollection.Set(String name, String value)
2019-01-30T12:24:44.6671432Z    at CallSite.Target(Closure , CallSite , Object , String , Object )
2019-01-30T12:24:44.6671625Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
2019-01-30T12:24:44.6671864Z    at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
2019-01-30T12:24:44.6672066Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-30T12:24:44.6672242Z    --- End of inner exception stack trace ---
2019-01-30T12:24:44.6672431Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-01-30T12:24:44.6672643Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-01-30T12:24:44.6672850Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-30T12:24:44.6673056Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-30T12:24:44.6673257Z    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2019-01-30T12:24:44.6673438Z    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2019-01-30T12:24:44.6673641Z    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2019-01-30T12:24:44.6674067Z    at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2019-01-30T12:24:44.6674237Z    at System.Management.Automation.CommandProcessorBase.Complete()
2019-01-30T12:24:44.6674384Z    --- End of inner exception stack trace ---
2019-01-30T12:24:44.6674549Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2019-01-30T12:24:44.6674749Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2019-01-30T12:24:44.6674968Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2019-01-30T12:24:44.6676779Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-01-30T12:24:44.6677108Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-01-30T12:24:44.6677426Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2019-01-30T12:24:44.6860859Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2019-01-30T12:24:44.6861964Z ##[section]Finishing: Unicorn Sync
```

**Comment by luuksommers** [comment]
I'll close the issue, I don't use sitecore anymore :) Thanks for your awesome pluging!
